# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Evoweb\StoreFinder\:
    resource: '../Classes/*'

  Evoweb\StoreFinder\Cache\CoordinatesCache:
    factory: ['Evoweb\StoreFinder\Cache\CoordinatesCache', 'getInstance']
    shared: false
    autoconfigure: false
    autowire: false

  Evoweb\StoreFinder\Command\ImportLocationsCommand:
    tags:
      - name: 'console.command'
        command: 'storefinder:import'
        description: 'Import locations from excel file into given storage folder (default 1)'
        schedulable: true

  Evoweb\StoreFinder\Command\GeocodeLocationsCommand:
    tags:
      - name: 'console.command'
        command: 'storefinder:geocode'
        description: 'Query google geocode service to get lat/lon for locations that are not geocode already'
        schedulable: true

  cache.store_finder.middleware_cache:
    class: 'TYPO3\CMS\Core\Cache\Frontend\FrontendInterface'
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments:
      $identifier: 'store_finder_middleware_cache'

  Evoweb\StoreFinder\Middleware\CategoryMiddleware:
    arguments:
      $contentRepository: '@Evoweb\StoreFinder\Domain\Repository\ContentRepository'
      $categoryRepository: '@Evoweb\StoreFinder\Domain\Repository\CategoryRepository'
      $eventDispatcher: '@Psr\EventDispatcher\EventDispatcherInterface'
      $cache: '@cache.store_finder.middleware_cache'
    public: true

  Evoweb\StoreFinder\Middleware\LocationMiddleware:
    arguments:
      $contentRepository: '@Evoweb\StoreFinder\Domain\Repository\ContentRepository'
      $locationRepository: '@Evoweb\StoreFinder\Domain\Repository\LocationRepository'
      $geocodeService: '@Evoweb\StoreFinder\Service\GeocodeService'
      $eventDispatcher: '@Psr\EventDispatcher\EventDispatcherInterface'
      $cache: '@cache.store_finder.middleware_cache'
    public: true

  Evoweb\StoreFinder\EventListener\TceMainListener:
    public: true

  Evoweb\StoreFinder\ViewHelpers\Form\SelectCountriesViewHelper:
    public: true

  SJBR\StaticInfoTables\Domain\Repository\TerritoryRepository:
    public: true
