# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Evoweb\StoreFinder\:
    resource: '../Classes/*'

  Evoweb\StoreFinder\Cache\CoordinatesCache:
    factory: ['Evoweb\StoreFinder\Cache\CoordinatesCache', 'getInstance']
    shared: false
    autoconfigure: false
    autowire: false

  Evoweb\StoreFinder\Command\ImportLocationsCommand:
    tags:
      - name: 'console.command'
        command: 'storefinder:import'
        description: 'Import locations from excel file into given storage folder (default 1)'
        schedulable: true

  Evoweb\StoreFinder\Command\GeocodeLocationsCommand:
    tags:
      - name: 'console.command'
        command: 'storefinder:geocode'
        description: 'Query google geocode service to get lat/lon for locations that are not geocode already'
        schedulable: true

  Evoweb\StoreFinder\EventListener\TceMainListener:
    public: true

  Evoweb\StoreFinder\ViewHelpers\Form\SelectCountriesViewHelper:
    public: true

  SJBR\StaticInfoTables\Domain\Repository\TerritoryRepository:
    public: true

  cache.store_finder_middleware_cache:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['store_finder_middleware_cache']

  Evoweb\StoreFinder\Cache\MiddlewareCache:
    arguments:
      $frontendInterface: '@cache.store_finder_middleware_cache'
