# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Evoweb\StoreFinder\:
    resource: '../Classes/*'

  Evoweb\StoreFinder\Cache\CoordinatesCache:
    factory: ['Evoweb\StoreFinder\Cache\CoordinatesCache', 'getInstance']
    shared: false
    autoconfigure: false
    autowire: false

  Evoweb\StoreFinder\EventListener\TceMainListener:
    public: true

  Evoweb\StoreFinder\Command\ImportLocationsCommand:
    tags:
      - name: 'console.command'
        command: 'storefinder:import'
        description: 'Import locations from excel file into given storage folder (default 1)'
        schedulable: true

  Evoweb\StoreFinder\Command\GeocodeLocationsCommand:
    tags:
      - name: 'console.command'
        command: 'storefinder:geocode'
        description: 'Query google geocode service to get lat/lon for locations that are not geocode already'
        schedulable: true

  SJBR\StaticInfoTables\Domain\Repository\TerritoryRepository:
    public: true
